### ISSUE TITLE
Parsing metadata and adding to the database

### ISSUE THREAD

**Issue by jazzguitarist** [dicarlolab/ThreeDWorld#43]
-no metadata? Investigate
-fetch from shapenets database
-subset?
-add info.version property to database with correct version nums for old and new (v1, v2)

**Comment by yamins81** [comment]
@pbashivan @qbilius what is the status of this?

**Comment by qbilius** [comment]
- v2 has been prepared and DB updated with the info.version key available.
- Fetching is not implemented. There is a dldata object but I haven't made the fetch yet. Also, models have not been posted on S3. Reason: No time for that + some of them were failing to convert in vhacd so the idea was to contact ShapeNet team to get this resolved. I never did that though as other things got in the way.
- Subsetting was done once for the b06 build but a more general routine is not fully done. There were issues how to properly do this so that the resulting objects do not overlap in categories. I don't think we ever decided how this is done best. I should look at it again.

**Comment by yamins81** [comment]
Ok thanks @qbilius  for the update, let's discuss this more tomorrow
