### ISSUE TITLE
Test timing for image generation in the new code

### ISSUE THREAD

**Issue by yamins81** [dicarlolab/ThreeDWorld#60]

**Comment by pbashivan** [comment]
I'm trying to import some of the generated prefabs to my machine (mac) to try the timing test.
I tried two ways to do this. 
1. Copied the prefabs into my machine. In this case prefabs were just placeholders and did not contain anything about the object. I guess this might be because of the dependencies on other materials and so.
2. I then tried exporting some of the prefabs on windows machine and importing them in mac. This way the prefabs were loaded but the textures are not properly loaded. 

Anybody has any ideas?

**Comment by pbashivan** [comment]
I bundled 216 prefabs from shapenet once into a single bundle and once to one bundle per prefab. Populating a scene with all the prefabs loaded in two ways ended up with no difference between the two methods.
I'm going to move forward with changing ProceduralGeneration code to load the assets from separate bundles (one bundle for each prefab). 
I'm putting the generated bundles in Assets/AssetBundles directory under /threedworld.
Let me know if you have any comments.

**Comment by chengxuz** [comment]
@pbashivan I am closing this. Feel free to re-open this if needed.
